name: Publish Packages

on:
  push:
    tags:
      - '*'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0       # full history so the tag is reachable
            fetch-tags: true     # ensure tags are fetched

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libmodbus-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.tar.gz
            build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
