name: Publish Packages (amd64 + arm64)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-package:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            deb_arch: amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            deb_arch: arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libmodbus-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=${{ matrix.deb_arch }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package
        run: |
          set -euo pipefail
          cd build
          cpack

      - name: Collect and rename artifacts
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          mkdir -p dist

          # TGZ: produced as libfronius-<version>.tar.gz -> append linux-arch once
          for f in build/*.tar.gz; do
            base=$(basename "$f")
            new="${base%.tar.gz}-linux-${{ matrix.arch }}.tar.gz"
            cp "$f" "dist/$new"
          done

          # DEB: already Debian-style (libfronius_<version>_<arch>.deb) -> copy as-is
          for f in build/*.deb; do
            cp "$f" "dist/$(basename "$f")"
          done

          echo "Packaged files:"
          ls -l dist || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "packages-linux-${{ matrix.arch }}"
          path: dist/*
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display downloaded files
        run: |
          echo "Files to release:"
          find dist -type f -maxdepth 2 -print

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
